#!/bin/zsh

setup() {
  ZOTFILES="${0:a:h}"
  brew update
}

install_prefs() {
  # Link and read iterm2 prefs
  ln -sf "$ZOTFILES/com.googlecode.iterm2.plist" "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
  defaults read "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
}

install_omz() {
  if [ ! -d "$HOME/.ohmyzsh" ]; then
    git clone git@github.com:ohmyzsh/ohmyzsh.git ~/.ohmyzsh
  fi
  chsh -s /bin/zsh
}

install_powerline() {
  echo "Installing powerline fonts"
  pushd "$HOME/workspace"
    if [ ! -d "powerline-fonts" ]; then
      git clone git@github.com:powerline/fonts.git powerline-fonts
    fi
    pushd powerline-fonts
      ./install.sh
    popd
  popd
}

install_neovim_python() {
  echo "Setting up neovim Python support"
  local venv_dir="$HOME/.config/nvim/venv"
  if [ ! -d "$venv_dir" ]; then
    mkdir -p "$HOME/.config/nvim"
    /opt/homebrew/bin/python3 -m venv "$venv_dir"
  fi
  "$venv_dir/bin/pip" install --upgrade pip pynvim

  # Ensure init.vim points to the venv python
  local init_vim="$HOME/.config/nvim/init.vim"
  if [ -f "$init_vim" ]; then
    if ! grep -q "python3_host_prog" "$init_vim"; then
      echo "let g:python3_host_prog = expand('~/.config/nvim/venv/bin/python')" >> "$init_vim"
    fi
  else
    mkdir -p "$HOME/.config/nvim"
    echo "let g:python3_host_prog = expand('~/.config/nvim/venv/bin/python')" > "$init_vim"
  fi
}

install_luan_vim() {
  echo "Installing luan's vimfiles"
  if [ ! -d "$HOME/.vim" ]; then
    pushd "$HOME"
      git clone git@github.com:luan/vimfiles.git .vim
      pushd .vim
        ./install
      popd
    popd
  fi
}

link_dotfiles() {
  ln -sf "$ZOTFILES/.zshrc" "$HOME/.zshrc"
  ln -sf "$ZOTFILES/zagnoster.zsh-theme" "$HOME/.ohmyzsh/themes/zagnoster.zsh-theme"
  cp "$ZOTFILES/.gitconfig" "$HOME/.gitconfig"
}

set_defaults() {
  defaults write NSGlobalDomain KeyRepeat 1
  defaults write NSGlobalDomain InitialKeyRepeat 15
}

main() {
  setup

  brew bundle
  brew link git --force

  install_prefs
  install_powerline
  install_omz
  install_neovim_python
  link_dotfiles
  install_luan_vim

  set_defaults
}

main $@
